In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
#create tensors using tf.constant()
scalar = tf.constant(13)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [3]:
#check dimension of the scalar 
scalar.ndim

0

In [4]:
#create vetcor
vector = tf.constant([10,13,17])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 13, 17], dtype=int32)>

In [5]:
#check dimension of the vector
vector.ndim

1

In [6]:
#create a matrix - matrix has more than one dimension
matrix = tf.constant([
    [10,23],
    [13,19]
])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 23],
       [13, 19]], dtype=int32)>

In [7]:
#dimension of the matrix
matrix.ndim

2

In [8]:
#create another matrix
another_matrix = tf.constant([
    [10.,25.,11.],
    [2.,5.,13.]
],
dtype=tf.float16
)

another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10., 25., 11.],
       [ 2.,  5., 13.]], dtype=float16)>

### creating tensors with tf.variable

In [9]:
#creating a changable tensor
changable_tensor = tf.Variable([10,20,30])
unchangable_tensor = tf.constant([10,20,30])

changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>)

In [10]:
#let's change elemets in changable tensnsor
changable_tensor[0].assign(13)
changable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([13, 20, 30], dtype=int32)>

### Creating Random tensors

In [11]:
#creating two random but the same tensors
random_1 = tf.random.Generator.from_seed(20)
random_1=random_1.normal(shape=(2,2))

#second random tensor
random_2 = tf.random.Generator.from_seed(20)
random_2 = random_2.normal(shape=(2,2))

random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor

In [12]:
not_shuffled = tf.constant([
    [10, 7, 9],
    [12, 34, 51],
    [1, 5, 8]
])

# The shuffled elemts will keep on changing because we have not set the global
# and operation random seed
shuffled = tf.random.shuffle(not_shuffled)

shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  9],
       [12, 34, 51],
       [ 1,  5,  8]], dtype=int32)>

#### Generating constant random tensors by setting the operational and global seed

In [13]:
tf.random.set_seed(42) #setting global seed
tf.random.shuffle(not_shuffled, seed=42) #the seed value here is not mandatory

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  9],
       [12, 34, 51],
       [ 1,  5,  8]], dtype=int32)>

### Other ways for creating tensors

In [14]:
import numpy as np

# a = np.ones(shape = (2,3)) using numpy to initilize
tf.ones(shape=(3,3)),tf.zeros([5,5])


(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>)

#### Turn numpy into tensors - The main difference between numpy and tensors
#### is that tensors can be run on a GPU for faster computation

In [15]:
#creating a numpy and assigning it intial values
numpy_A = np.arange(2, 26, dtype = np.int32)
#numpy_A = numpy_A.reshape([1,24])
numpy_A.shape



(24,)

In [16]:
#Creating tensors from the numpy arrays
A = tf.constant(numpy_A, shape = (3,8))
B = tf.constant(numpy_A)

B,A

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25]], dtype=int32)>)

## Getting Additional info from a tensor

When dealing with tensors the below attributes are critical for your operations: <br>

* Shape---------------shape
* Rank (dimension) ---------------- ndim
* Axis
* Size ------------------ number of elements in the tensor




In [17]:
tensor_rank2 = tf.ones(shape = (3,3))
tensor_rank2.shape, tensor_rank2.ndim, tf.size(tensor_rank2), tf.size(tensor_rank2).numpy()

(TensorShape([3, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=9>, 9)

In [18]:
print("The number of elements in 0 axis= ",tensor_rank2.shape[0] )
print("The number of elements in last axis= ",tensor_rank2.shape[-1] )

The number of elements in 0 axis=  3
The number of elements in last axis=  3


In [19]:
#creating a tensor
rank2_tensor = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])

In [20]:
#Getting first element on each row of our rank 2 tensor
rank2_tensor[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [21]:
# Adding Extra dimension to our rank2 tensor
rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [22]:
# Adding Extra dimension to our rank2 tensor
rank3_tensor = rank2_tensor[:,:,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [23]:
#Adding on the first axis
rank3_tensor = tf.expand_dims(rank2_tensor, axis=0)
rank3_tensor

<tf.Tensor: shape=(1, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]], dtype=int32)>

In [24]:
#Adding on the last axis
rank3_tensor = tf.expand_dims(rank2_tensor, axis=-1)
rank3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

## Matrix Multiplication
### We mainly use the following methods:
* tf.tensordot(a,b, axis=)
* tf.matmul(a,b)
* @
### Generally when performing dot product, transposing instead of reshaping 
### is used to enable all the matrices follow matrix rules of multiplication

In [25]:
tensor1 = tf.constant([
                   [10,7],
                   [5,8]])

In [26]:
#Elementwise multiplication
tensor1 * tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 25,  64]], dtype=int32)>

In [27]:
#Dot product multiplication
tf.matmul(tensor1,tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 126],
       [ 90,  99]], dtype=int32)>

### For the dot product (matrix multiplication) to take place.
### The number of innner dimensions must match. Example below
* 3 x 2, 2 x 3---------------> the 2 values are matching.
* 3x2, 3x2-----------> will not work because the inner dimensions are different
### The resulting tensor or matrix after the dot product operation 
### will be equal to the outer dimension. Example below:
* (3,2) x (2,3) --------------------> (3,3)

In [28]:
#3x2 tensor
tensor1 = tf.constant([
    [1,2],
    [3,4],
    [5,6]
]
)

#3x2 tensor
tensor2 = tf.constant([
    [7,8],
    [9,10],
    [11,12]
]
)

In [29]:
# for the dot product to work we must first reashape our tensor such that
# the inner dimensions of the tensor must first match.
tensor2_reshaped = tf.reshape(tensor2, shape=(2,3))
dot_product = tf.matmul(tensor1, tensor2_reshaped)
dot_product1 = tensor1 @ tensor2_reshaped
print("The reshaped tensor is = ", tensor2_reshaped)
print("The Dot product of the tensor is = ", dot_product )
print("Alternative Dot product of the tensor is = ", dot_product1 )

The reshaped tensor is =  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
The Dot product of the tensor is =  tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
Alternative Dot product of the tensor is =  tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


### The difference between Transpose and reshape is it flips the axes of the matrices

In [30]:
print("The first tensor value ", tensor1)
print("Tensor value after reshape", tf.reshape(tensor1, shape=(2,3)))
print("Tensor value after Transpose", tf.transpose(tensor1))

The first tensor value  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Tensor value after reshape tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Tensor value after Transpose tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


### The difference between tf.matmul() and tf.tensordot()

In [31]:
print("Tensor1 value = ", tensor1)
print("Tensor2 value = ", tensor2_reshaped)
print("\n")
print("Matrix multiplication value using matmul = ",tf.matmul(tensor1,tensor2_reshaped))
print("\n")
print("Matrix multiplication value using tensordot = ",tf.tensordot(tensor1,tensor2_reshaped, axes=1))


Tensor1 value =  tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
Tensor2 value =  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


Matrix multiplication value using matmul =  tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


Matrix multiplication value using tensordot =  tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)


### Casting from one datatype to another datatype

In [32]:
A = tf.constant([
    [1,2], 
    [3,4]
])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [33]:
#converting from int32 to float32
B = tf.cast(A, dtype=tf.float32)
B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

## Tensorflow Aggregation
### The different forms of tensorflow aggregation include the following:
* abs()-------------> return positive values 
* reduce_sum
* reduce_mean
* reduce_min
* reduce_max

In [34]:
#getting absolute values from tensor
A = tf.constant([1,-4,-5])
tf.abs(A)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 5], dtype=int32)>

In [37]:
#creating random tesnor of size 24
B = tf.constant(np.random.randint(1,28,size=24))
B =tf.reshape(B, shape=(4,6))
B

<tf.Tensor: shape=(4, 6), dtype=int64, numpy=
array([[ 3, 20, 13, 14, 21,  4],
       [10,  1, 21, 25,  2,  8],
       [22, 18,  3,  7, 18,  7],
       [ 1, 16, 25, 22, 14, 10]])>

In [41]:
print("sum of the tesnor = ", tf.reduce_sum(B))
print("max value of the tesnor = ", tf.reduce_max(B))
print("min value of the tesnor = ", tf.reduce_min(B))

sum of the tesnor =  tf.Tensor(305, shape=(), dtype=int64)
max value of the tesnor =  tf.Tensor(25, shape=(), dtype=int64)
min value of the tesnor =  tf.Tensor(1, shape=(), dtype=int64)


## Finding the postional Maximum and Minimum

In [51]:
#Creating a tensor with random elements for finding positional
#maximum and minimum values
tf.random.set_seed(42)
A = tf.random.uniform(shape=[50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [54]:
#Find the positional maximum
# we will use argmax(), same as np.argmax()
#returns the index of the maximum value along the axis
tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [57]:
#the largest value in the tensor
A[tf.argmax(A)], tf.reduce_max(A) 

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [59]:
#find the minimum value using the positional minimum value
A[tf.argmin(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Sequeezing a tensor (Removing All single dimensions)

In [63]:
#Creating tesnor with random values
tf.random.set_seed(42)
D = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,50))
D_squeeze = tf.squeeze(D)
D.shape, D_squeeze.shape

(TensorShape([1, 1, 50]), TensorShape([50]))

## One-hot Encoding in tensors

In [71]:
### list of colors represensted below
colors = [0,1,2] #representing the colors - blue, red and green

one_hot_encoded_tensor = tf.one_hot(colors, depth=3)
one_hot_encoded_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

### More maths operations with tensors


In [73]:
H=tf.range(1,20)
H

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int32)>

In [75]:
tf.square(H)

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)>

In [77]:
##when using sqaure roots the method requires non-integer types
## Hence we must first convert out integers to floats
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249, 3.4641016,
       3.6055512, 3.7416575, 3.8729835, 4.       , 4.1231055, 4.2426405,
       4.358899 ], dtype=float32)>

### Numpy and tensors are fully compatible

In [81]:
#creating numpy arrays from tensors.
numpy_A = np.array(tf.constant([1,2,3]))
tensor_A= tf.constant(np.array([1,2,3]))

print("The numpy value is = ", numpy_A)
print("The tensor value is = ", tensor_A)

The numpy value is =  [1 2 3]
The tensor value is =  tf.Tensor([1 2 3], shape=(3,), dtype=int64)


## Getting access to the GPU in tesnsorflow
### If we have a CUDA enabled GPU tensorflow will automatically use it whenever possible.

In [87]:
tf.config.list_physical_devices(
    device_type=None
)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [88]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [89]:
#check type of gpu u are using
!nvidia-smi

Fri Jul 30 13:39:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   58C    P8    N/A /  N/A |   3825MiB /  4040MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------